In [10]:
import unittest
import numpy as np
from models.softmax_regression import SoftmaxRegression


class TestActivation(unittest.TestCase):
    """ The class containing all test cases for this assignment"""

    def setUp(self):
        """Define the functions to be tested here."""
        self.model = SoftmaxRegression()

    def test_sigmoid(self):
        x = np.array([[-1.48839468, -0.31530738],
                      [-0.28271176, -1.00780433],
                      [0.66435418, 1.2537461],
                      [-1.64829182, 0.90223236]])
        y = np.array([[0.1841628, 0.4218198],
                      [0.42978908, 0.26740977],
                      [0.66023782, 0.77794766],
                      [0.16133995, 0.71140804]])
        outs = self.model.sigmoid(x)
        diff = np.sum(np.abs((outs - y)))
        self.assertAlmostEqual(diff, 0, places=7)

In [15]:
x = np.array([[-1.48839468, -0.31530738],
              [-0.28271176, -1.00780433],
              [0.66435418, 1.2537461],
              [-1.64829182, 0.90223236]])
y = np.array([[0.1841628, 0.4218198],
              [0.42978908, 0.26740977],
              [0.66023782, 0.77794766],
              [0.16133995, 0.71140804]])
outs = 1/(1+np.exp(-x))
#outs = self.model.sigmoid(x)
diff = np.sum(np.abs((outs - y)))
#self.assertAlmostEqual(diff, 0, places=7)

In [3]:
x

array([[-1.48839468, -0.31530738],
       [-0.28271176, -1.00780433],
       [ 0.66435418,  1.2537461 ],
       [-1.64829182,  0.90223236]])

In [4]:
outs

array([[0.1841628 , 0.4218198 ],
       [0.42978908, 0.26740977],
       [0.66023782, 0.77794766],
       [0.16133995, 0.71140804]])

In [5]:
np.sum(np.abs((outs - y)))

2.0660873317757122e-08

In [6]:
np.abs((outs - y))

array([[5.66854369e-10, 9.34511468e-10],
       [2.26673047e-09, 3.29724570e-09],
       [4.74917228e-09, 4.66435790e-09],
       [1.35177930e-09, 2.83022183e-09]])

In [7]:
y[1]

array([0.42978908, 0.26740977])

In [10]:
outs[1]

array([0.42978908, 0.26740977])

In [13]:
test = TestActivation()
test.assertAlmostEqual()