In [75]:
import numpy as np
from scipy import linalg
from cvxpy import *
A = np.matrix([[1, 1, 1, 0, 0],
[-2, 1, 0, 1, 0],
[2, 1, 0, 0, 1]])
b = np.array([4, 2, 6])
c = np.array([-1, -2, 0, 0, 0])
# put in the indices of the basic variables, ranging from 1, 2,..., 5
def ComputeBasicVar(Ind1, Ind2, Ind3):
    Ind1 -= 1
    Ind2 -= 1
    Ind3 -= 1
    A_B = A[:, (Ind1, Ind2, Ind3)]
    c_B = c[(Ind1, Ind2, Ind3),]
    print("A_B = ")
    print(A_B)
    print("c_B = ")
    print(c_B)
    print("x_B = ")
    print(linalg.inv(A_B).dot(b))
    #print("x_B = [x_{0}, x_{1}, x_{2}] = ".format(Ind1 + 1, Ind2 + 1, Ind3 + 1))
    #print(x_B)

In [76]:
print(ComputeBasicVar(3,4,5 ))

A_B = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
c_B = 
[0 0 0]
x_B = 
[4. 2. 6.]
None


In [83]:
print(ComputeBasicVar(1,3,5))   

A_B = 
[[ 1  1  0]
 [-2  0  0]
 [ 2  0  1]]
c_B = 
[-1  0  0]
x_B = 
[-1.  5.  8.]
None


In [78]:
print(ComputeBasicVar(1,4,5))

A_B = 
[[ 1  0  0]
 [-2  1  0]
 [ 2  0  1]]
c_B = 
[-1  0  0]
x_B = 
[ 4. 10. -2.]
None


In [79]:
print(ComputeBasicVar(1,3,4))

A_B = 
[[ 1  1  0]
 [-2  0  1]
 [ 2  0  0]]
c_B = 
[-1  0  0]
x_B = 
[3. 1. 8.]
None


In [80]:
print(ComputeBasicVar(2,3,4))

A_B = 
[[1 1 0]
 [1 0 1]
 [1 0 0]]
c_B = 
[-2  0  0]
x_B = 
[ 6. -2. -4.]
None


In [84]:
print(ComputeBasicVar(2,4,5))

A_B = 
[[1 0 0]
 [1 1 0]
 [1 0 1]]
c_B = 
[-2  0  0]
x_B = 
[ 4. -2.  2.]
None


In [85]:
print(ComputeBasicVar(2,3,5))

A_B = 
[[1 1 0]
 [1 0 0]
 [1 0 1]]
c_B = 
[-2  0  0]
x_B = 
[2. 2. 4.]
None


In [86]:
print(ComputeBasicVar(1,2,5))

A_B = 
[[ 1  1  0]
 [-2  1  0]
 [ 2  1  1]]
c_B = 
[-1 -2  0]
x_B = 
[0.66666667 3.33333333 1.33333333]
None


In [88]:
print(ComputeBasicVar(1,2,4))

A_B = 
[[ 1  1  0]
 [-2  1  1]
 [ 2  1  0]]
c_B = 
[-1 -2  0]
x_B = 
[2. 2. 4.]
None


In [89]:
print(ComputeBasicVar(1,2,3))

A_B = 
[[ 1  1  1]
 [-2  1  0]
 [ 2  1  0]]
c_B = 
[-1 -2  0]
x_B = 
[ 1.  4. -1.]
None
