In [13]:
from scipy import linalg
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
linalg.kron(a, b)

array([[ 5,  6, 10, 12],
       [ 7,  8, 14, 16],
       [15, 18, 20, 24],
       [21, 24, 28, 32]])

In [14]:
linalg.khatri_rao(a, b)

array([[ 5, 12],
       [ 7, 16],
       [15, 24],
       [21, 32]])

In [19]:
linalg.inv(linalg.kron(a, b))

array([[ 8.  , -6.  , -4.  ,  3.  ],
       [-7.  ,  5.  ,  3.5 , -2.5 ],
       [-6.  ,  4.5 ,  2.  , -1.5 ],
       [ 5.25, -3.75, -1.75,  1.25]])

In [20]:
linalg.kron(linalg.inv(a), linalg.inv(b))

array([[ 8.  , -6.  , -4.  ,  3.  ],
       [-7.  ,  5.  ,  3.5 , -2.5 ],
       [-6.  ,  4.5 ,  2.  , -1.5 ],
       [ 5.25, -3.75, -1.75,  1.25]])